"""Supabase Storage uploads for generated ad images.

Why this exists
---------------
Image-generation providers (Replicate, OpenAI) hand back URLs that expire
within hours. To make ads viewable for the lifetime of the row, we always
download the generated bytes server-side and re-upload them to a
**Supabase Storage** bucket — that URL is then what gets persisted in
``ads.image_url`` and returned to clients.

Convention
----------
Every file lives at ``{user_id}/{uuid4}.png`` inside the bucket named by
``SUPABASE_STORAGE_BUCKET`` (defaults to ``adess``). The first path segment
matching ``user_id`` is what our storage-RLS policy keys on, so this layout
is mandatory.

Auth
----
We sign storage requests with the **service-role** key, not the user JWT.
The user identity is encoded in the path; RLS still applies for reads from
other paths, but writes through this backend module are trusted because the
backend is the one calling the upload.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import uuid4

from storage3 import AsyncStorageClient

from backend.config import Settings, get_settings

# ── Public errors ─────────────────────────────────────────────────────


class StorageError(RuntimeError):
    """Raised when a Supabase Storage upload fails."""


# ── Result shape ──────────────────────────────────────────────────────


@dataclass(slots=True, frozen=True)
class UploadResult:
    """Plain-data return value for :func:`upload_image`.

    Matches :class:`backend.schemas.ImageResponse` fields ``image_url`` and
    ``storage_path`` so the router can pass them straight through.
    """




    url: str
    path: str
    bucket: str


# ── Internals ─────────────────────────────────────────────────────────


_DEFAULT_MIME = "image/png"


def _content_type_for(image_bytes: bytes) -> str:
    """Sniff the magic bytes; fall back to PNG."""
    if image_bytes[:8] == b"\x89PNG\r\n\x1a\n":
        return "image/png"
    if image_bytes[:3] == b"\xff\xd8\xff":
        return "image/jpeg"
    if image_bytes[:4] == b"RIFF" and image_bytes[8:12] == b"WEBP":
        return "image/webp"
    return _DEFAULT_MIME


def _extension_for(content_type: str) -> str:
    return {
        "image/png": "png",
        "image/jpeg": "jpg",
        "image/webp": "webp",
    }.get(content_type, "png")


def _storage_client(settings: Settings) -> AsyncStorageClient:
    """Build an :class:`AsyncStorageClient` signed as service-role."""
    admin = settings.admin_supabase_key
    if admin is None:
        raise StorageError(
            "Supabase admin key missing — set SUPABASE_SECRET_KEY or "
            "SUPABASE_SERVICE_ROLE_KEY to upload to storage."
        )

    base = str(settings.supabase_url).rstrip("/")
    # storage3 expects a trailing slash; without one it emits a warning and
    # auto-corrects. Provide it explicitly.
    url = f"{base}/storage/v1/"
    token = admin.get_secret_value()
    headers = {
        "apiKey": token,
        "Authorization": f"Bearer {token}",
    }
    return AsyncStorageClient(url, headers)


# ── Public API ────────────────────────────────────────────────────────


async def upload_image(
    user_id: str,
    image_bytes: bytes,
    *,
    filename: str | None = None,
    settings: Settings | None = None,
) -> UploadResult:
    """Upload ``image_bytes`` to Supabase Storage and return public URL + path.

    :param user_id: Owner of the image; becomes the first path segment.
    :param image_bytes: Raw bytes from the image generator. Required.
    :param filename: Optional override for the storage key; defaults to a
        random ``{uuid4}.{ext}`` so callers never need to invent one.
    """
    if not user_id:
        raise StorageError("user_id is required.")
    if not image_bytes:
        raise StorageError("image_bytes is empty.")

    s = settings or get_settings()
    bucket = s.supabase_storage_bucket
    content_type = _content_type_for(image_bytes)
    ext = _extension_for(content_type)
    name = filename or f"{uuid4()}.{ext}"
    path = f"{user_id}/{name}"

    client = _storage_client(s)
    try:
        await client.from_(bucket).upload(
            path,
            image_bytes,
            file_options={"content-type": content_type, "upsert": "false"},
        )
    except Exception as exc:  # pragma: no cover — network errors at runtime
        raise StorageError(f"Supabase upload failed for {path!r}: {exc}") from exc

    try:
        public_url = await client.from_(bucket).get_public_url(path)
    except Exception as exc:  # pragma: no cover
        raise StorageError(f"Could not compute public URL for {path!r}: {exc}") from exc

    return UploadResult(url=public_url, path=f"{bucket}/{path}", bucket=bucket)


__all__ = ["StorageError", "UploadResult", "upload_image"]
